ValueSet: AHIPReadingLanguagePreferences
Id: ahip-reading-language-prereferences
Title: "AHIP Reading Language Preferences"
Description: "Used as the answer options for the reading language preferences question in the Language Section, capturing the languages and formats a patient prefers when reading health care materials."
* ^version = "0.0.1"
* ^status = #active
* ^experimental = false
* ^date = "2026-08-25T00:00:00-04:00"
* ^publisher = "AHIP"
* ^contact.name = "AHIP"
* ^jurisdiction = urn:iso:std:iso:3166#US
* ^copyright = "Used by permission of HL7 International, all rights reserved Creative Commons License"
* $isolang#am "Amharic"
* $isolang#ar "Arabic"
* $isolang#ath "Athabaskan (Na-Dene)"
* $isolang#bn "Bengali"
* $isolang#my "Burmese"
* $isolang#ch "Chamorro"
* $isolang#chr "Cherokee"
* $isolang#zh-Hans "Chinese (Simplified)"
* $isolang#zh-Hant "Chinese (Traditional)"
* $isolang#chk "Chuukese"
* $isolang#cro "Crow"
* $isolang#da "Danish"
* $isolang#dak "Dakota"
* $isolang#prs "Dari"
* $isolang#nl "Dutch"
* $isolang#en "English"
* $isolang#fj "Fijian"
* $isolang#fr "French"
* $isolang#de "German"
* $isolang#el "Greek"
* $isolang#ht "Haitian Creole"
* $isolang#haw "Hawaiian"
* $isolang#he "Hebrew"
* $isolang#hi "Hindi"
* $isolang#hmn "Hmong"
* $isolang#id "Indonesian"
* $isolang#ik "Inupiaq"
* $isolang#it "Italian"
* $isolang#ja "Japanese"
* $isolang#kar "Karen"
* $isolang#kkh "Karenni"
* $isolang#km "Central Khmer"
* $isolang#kos "Kosraean"
* $isolang#ko "Korean"
* $isolang#ku "Kurdish"
* $isolang#lkt "Lakota (Sioux)"
* $isolang#lo "Lao"
* $isolang#lt "Lithuanian"
* $isolang#mh "Marshallese"
* $isolang#mus "Muscogee"
* $isolang#nv "Navajo(Diné bazaad)"
* $isolang#ne "Nepali"
* $isolang#no "Norwegian"
* $isolang#oj "Ojibwe"
* $isolang#ood "O'oodham"
* $isolang#pau "Palauan"
* $isolang#ps "Pashto"
* $isolang#pdc "Pennsylvania Dutch (Pennsylvania German)"
* $isolang#fa "Persian (Farsi)"
* $isolang#pl "Polish"
* $isolang#pon "Pohnpeian"
* $isolang#pt "Portuguese"
* $isolang#ru "Russian"
* $isolang#sm "Samoan"
* $isolang#si "Sinhala"
* $isolang#so "Somali"
* $isolang#es "Spanish"
* $isolang#sw "Swahili"
* $isolang#sv "Swedish"
* $isolang#tl "Tagalog"
* $isolang#tnq "Taino"
* $isolang#ta "Tamil"
* $isolang#th "Thai"
* $isolang#tli "Tlingit"
* $isolang#to "Tongan"
* $isolang#tpi "Tok Pisin"
* $isolang#uk "Ukrainian"
* $isolang#ur "Urdu"
* $isolang#vi "Vietnamese"
* $isolang#cy "Welsh"
* $isolang#apw "Western Apache"
* $isolang#yap "Yapese"
* $isolang#yi "Yiddish"
* $isolang#ypk "Yu'pik"
* $isolang#zun "Zuni"
* $ReadingMode#braille "Braille"
* $ReadingMode#large-print "Large Print"
* $ReadingMode#digital-spoken "Digital Documents that Can Be Spoken Out Loud​"
* $nullFlavor#ASKU "I don't know"
* $AHIPDemoAdditionalNullFlavor#CNTR "I choose not to respond at this time"
