ValueSet: AHIPSpeakingLanguagePreferences
Id: ahip-speaking-language-prereferences
Title: "AHIP Speaking Language Preferences"
Description: "Used as the answer options for the speaking language preferences question in the Language Section, capturing the language(s) a patient feels most comfortable speaking about their health care. Based on IETF 3066 Language Codes"
* insert DEMoStandardMetadata
* ^version = "0.0.1"
* ^status = #active
* ^experimental = false
* ^date = "2026-08-25T00:00:00-04:00"
* ^contact.name = "AHIP"
* ^jurisdiction = urn:iso:std:iso:3166#US
* ^copyright = """
This value set includes codes from IETF BCP 47, Tags for Identifying Languages (RFC 5646 and RFC 4647), published by the Internet Engineering Task Force (IETF). The BCP 47 documents are copyright © IETF Trust and the persons identified as the document authors. For more information see https://www.rfc-editor.org/info/bcp47.

This material derives from the HL7 Terminology (THO). THO is copyright ©1989+ Health Level Seven International and is made available under the CC0 designation. For more licensing information see: https://terminology.hl7.org/license.html

This value set includes content developed through the DEMo Initiative and is subject to joint copyright of America's Health Insurance Plans (AHIP) and Health Level Seven International (HL7).
"""
* $isolang#am "Amharic"
* $isolang#ar "Arabic"
* $isolang#ath "Athabaskan (Na-Dene)"
* $isolang#bn "Bengali"
* $isolang#my "Burmese"
* $isolang#yue "Cantonese"
* $isolang#ch "Chamorro"
* $isolang#chr "Cherokee"
* $isolang#chk "Chuukese"
* $isolang#cro "Crow"
* $isolang#da "Danish"
* $isolang#dak "Dakota"
* $isolang#prs "Dari"
* $isolang#nl "Dutch"
* $isolang#en "English"
* $isolang#fj "Fijian"
* $isolang#fr "French"
* $isolang#de "German"
* $isolang#el "Greek"
* $isolang#ht "Haitian Creole"
* $isolang#haw "Hawaiian"
* $isolang#he "Hebrew"
* $isolang#hi "Hindi"
* $isolang#hmn "Hmong"
* $isolang#id "Indonesian"
* $isolang#ik "Inupiaq"
* $isolang#it "Italian"
* $isolang#ja "Japanese"
* $isolang#kar "Karen"
* $isolang#kkh "Karenni"
* $isolang#km "Central Khmer"
* $isolang#kos "Kosraean"
* $isolang#ko "Korean"
* $isolang#ku "Kurdish"
* $isolang#lkt "Lakota (Sioux)"
* $isolang#lo "Lao"
* $isolang#lt "Lithuanian"
* $isolang#cmn "Mandarin"
* $isolang#mh "Marshallese"
* $isolang#mus "Muscogee"
* $isolang#nv "Navajo (Dine' bazaad)"
* $isolang#ne "Nepali"
* $isolang#no "Norwegian"
* $isolang#oj "Ojibwe"
* $isolang#ood "O'oodham"
* $isolang#pau "Palauan"
* $isolang#ps "Pashto"
* $isolang#pdc "Pennsylvania Dutch (Pennsylvania German)"
* $isolang#fa "Persian (Farsi)"
* $isolang#pl "Polish"
* $isolang#pon "Pohnpeian"
* $isolang#pt "Portuguese"
* $isolang#ru "Russian"
* $isolang#sm "Samoan"
* $isolang#si "Sinhala"
* $isolang#so "Somali"
* $isolang#es "Spanish"
* $isolang#sw "Swahili"
* $isolang#sv "Swedish"
* $isolang#tl "Tagalog"
* $isolang#tnq "Taino"
* $isolang#ta "Tamil"
* $isolang#th "Thai"
* $isolang#tli "Tlingit"
* $isolang#to "Tongan"
* $isolang#tpi "Tok Pisin"
* $isolang#uk "Ukrainian"
* $isolang#ur "Urdu"
* $isolang#vi "Vietnamese"
* $isolang#cy "Welsh"
* $isolang#apw "Western Apache"
* $isolang#yap "Yapese"
* $isolang#yi "Yiddish"
* $isolang#ypk "Yu'pik"
* $isolang#zun "Zuni"
* $isolang#ase "American Sign Language"
* $nullFlavor#ASKU "I don't know"
* $AHIPDemoAdditionalNullFlavor#CNTR "I choose not to respond at this time"
