ValueSet: AHIPReligionSpirituality
Id: ahip-religion-spirituality
Title: "AHIP Religion/Spirituality Value Set"
Description: "Used as the answer options for the religion, spirituality, or belief system question in the Spirituality and Other Considerations Section."
* ^version = "0.0.1"
* ^status = #active
* ^experimental = false
* ^date = "2026-08-25T00:00:00-04:00"
* ^publisher = "AHIP"
* ^contact.name = "AHIP"
* ^jurisdiction = urn:iso:std:iso:3166#US
* ^copyright = "Used by permission of HL7 International, all rights reserved Creative Commons License"
* $ReligionCodes#1006 "Animism"
* $ReligionCodes#1004 "Agnostic (not sure if there is a God)​"
* $ReligionCodes#1007 "Atheist (do not believe in God)​" 
* $ReligionCodes#1008 "Baha'I"
* $ReligionCodes#1059 "Buddhism"
* $AHIPDemoTemporaryCodes#CHRI "Christianity (e.g. Protestant, Roman Catholic, Russian Orthodox, Seventh-day Adventist)"
* $ReligionCodes#1043 "Church of Scientology"
* $ReligionCodes#1014 "Confucianism"
* $ReligionCodes#1020 "Hinduism"
* $ReligionCodes#1021 "Humanism"
* $ReligionCodes#1023 "Islam,Nation of Islam (Muslim)"
* $ReligionCodes#1025 "Jehovah's Witnesses"
* $ReligionCodes#1026 "Judaism (Jewish)"
* $ReligionCodes#1027 "Mormonism (Church of Jesus Christ of Latterday Saints/LDS)"
* $AHIPDemoTemporaryCodes#OBEA "Obeahism"
* $ReligionCodes#1037 "Paganism"
* $ReligionCodes#1044 "Shamanism"
* $ReligionCodes#1047 "Sikhism"
* $ReligionCodes#1050 "Taoism"
* $ReligionCodes#1052 "Unitarian Universalist"
* $ReligionCodes#1056 "VooDoo"
* $ReligionCodes#1060 "Zoroastrianism"
* $AHIPDemoTemporaryCodes#SBNR "Spiritual but not religious"
* $nullFlavor#ASKU "I don't know"
* $AHIPDemoAdditionalNullFlavor#CNTR "I choose not to respond at this time"
