ValueSet: AHIPReadingLanguagePreferences
Id: ahip-reading-language-prereferences
Title: "AHIP Reading Language Preferences"
Description: "Based on IETF 3066 Language Codes"
* ^version = "0.0.1"
* ^status = #draft
* ^experimental = false
* ^date = "2025-03-24T00:00:00-04:00"
* ^publisher = "AHIP"
* ^contact.name = "AHIP"
* ^jurisdiction = urn:iso:std:iso:3166#US
* ^copyright = "Used by permission of HL7 International, all rights reserved Creative Commons License"
* $isolang#am "Amharic"
* $isolang#ar "Arabic"
* $isolang#bn "Bengali"
* $isolang#my "Burmese"
* $isolang#yue "Cantonese"
* $isolang#chr "Cherokee"
* $isolang#chk "Chuukese"
* $isolang#cro "Crow"
* $isolang#dak "Dakota"
* $isolang#prs "Dari"
* $isolang#nl "Dutch"
* $isolang#en "English"
* $isolang#fa "Farsi"
* $isolang#fr "French"
* $isolang#de "German"
* $isolang#el "Greek"
* $isolang#ht "Haitian Creole"
* $isolang#haw "Hawaiian"
* $isolang#he "Hebrew"
* $isolang#hi "Hindi"
* $isolang#hmn "Hmong"
* $isolang#ik "Inupiaq"
* $isolang#it "Italian"
* $isolang#ja "Japanese"
* $isolang#kar "Karen"
* $isolang#kkh "Karenni"
* $isolang#km "Khmer"
* $isolang#ko "Korean"
* $isolang#lkt "Lakota (sioux)"
* $isolang#lo "Lao"
* $isolang#cmn "Mandarin"
* $isolang#mh "Marshallese"
* $isolang#mus "Muscogee"
* $isolang#nv "Navajo (Dine')"
* $isolang#oj "Ojibwe"
* $isolang#ood "O'oodham"
* $isolang#pdc "Pennsylvania Dutch (Pennsylvania German)"
* $isolang#ps "Pashto"
* $isolang#pl "Polish"
* $isolang#pon "Pohnpeian"
* $isolang#pt "Portuguese"
* $isolang#ru "Russian"
* $isolang#sm "Samoan"
* $isolang#so "Somali"
* $isolang#es "Spanish"
* $isolang#sw "Swahili"
* $isolang#sv "Swedish"
* $isolang#tl "Tagalog"
* $isolang#tnq "Taino"
* $isolang#th "Thai"
* $isolang#to "Tongan"
* $isolang#vi "Vietnamese"
* $isolang#apw "Western Apache"
* $isolang#yi "Yiddish"
* $isolang#zun "Zuni"
* $ReadingMode#braille "Braille"
* $ReadingMode#large-print "Large Print"
* $ReadingMode#digital-spoken "Digital Documents that Can Be Spoken Out Loud​"
* $nullFlavor#ASKU "I don't know"
* $AHIPDemoAdditionalNullFlavor#CNTR "I choose not to respond at this time"
* $AHIPDemoAdditionalNullFlavor#PSIN "Please specify if not listed above"
